#### Notes for later

In [1]:
import polars as pl
import plotly.express as px
import pandas as pd  
import plotly.graph_objects as go
import matplotlib.pyplot as plt
from matplotlib.dates import DateFormatter, date2num
import time
import csv

#### Load last month's data

In [2]:
last_month = time.localtime().tm_mon - 1

current_yr = time.localtime().tm_year

# handling if last month was January
if last_month == 0:
    last_month = 12
    current_yr = current_yr - 1


df = pl.read_csv(r'C:\Users\Denne\Documents\VSCodeProjects\FinancialStreamline2\BankStreamline\Data\DebitHistory.csv')

# Date work
df = df.with_columns(
                pl.col("Post Date").str.strptime(pl.Date, "%m/%d/%Y").alias("date")
                ).with_columns([
                pl.col("date").dt.month().alias("month"),
                pl.col("date").dt.day().alias("day"),
                pl.col("date").dt.year().alias("year")
                ]) \
        .filter((pl.col('month') == last_month) & 
                (pl.col('year') == current_yr)) \
        .with_columns(date = pl.concat_str([pl.col('year').cast(pl.Utf8), pl.lit('-'), pl.col('month').cast(pl.Utf8), pl.lit('-'), pl.col('day').cast(pl.Utf8)], separator="")) \
        .with_columns(monthName = pl.col("date").str.strptime(pl.Date, "%Y-%m-%d").dt.strftime("%b")) \
        .with_columns(weekDay = pl.col("date").str.strptime(pl.Date, "%Y-%m-%d").dt.strftime("%a")) \
        .with_columns(quarter = pl.col("date").str.strptime(pl.Date, "%Y-%m-%d").dt.quarter())
                        
# # cost column
df = df.with_columns(pl.col('Debit').fill_null(value=0)) \
        .with_columns(pl.col('Credit').fill_null(value=0)) \
        .with_columns(cost =pl.col('Debit') + pl.col('Credit')) \
        
# # the gate/clean up
df = df.filter(~pl.col('Description').str.contains('ELECTRONIC DEPOSIT MURPHY OIL USA PPAYROLL|Funds Transfer via Mobile')) \
        .filter(~pl.col('Description').str.contains('DEPOSIT|deposit|Deposit|WITHDRAWAL-CASH')) \
        .filter(~pl.col('Description').str.contains('Withdrawal LOAN PAYMENT TRANSFER')) \
        .rename({'Description': 'description'}) \
        .with_columns(cardType = pl.lit('Debit'))

print(len(df))
df.limit(3)

15

shape: (3, 16)
┌────────────────┬───────────┬───────┬─────────────────┬───┬─────────┬─────────┬────────┬──────────┐
│ Account Number ┆ Post Date ┆ Check ┆ description     ┆ … ┆ weekDay ┆ quarter ┆ cost   ┆ cardType │
│ ---            ┆ ---       ┆ ---   ┆ ---             ┆   ┆ ---     ┆ ---     ┆ ---    ┆ ---      │
│ str            ┆ str       ┆ str   ┆ str             ┆   ┆ str     ┆ i8      ┆ f64    ┆ str      │
╞════════════════╪═══════════╪═══════╪═════════════════╪═══╪═════════╪═════════╪════════╪══════════╡
│ ***0530002     ┆ 3/31/2026 ┆ null  ┆ ACH Withdrawal  ┆ … ┆ Tue     ┆ 1       ┆ 139.0  ┆ Debit    │
│                ┆           ┆       ┆ SUMMIT SUA      ┆   ┆         ┆         ┆        ┆          │
│                ┆           ┆       ┆ BILL…           ┆   ┆         ┆         ┆        ┆          │
│ ***0530002     ┆ 3/25/2026 ┆ null  ┆ ACH Withdrawal  ┆ … ┆ Wed     ┆ 1       ┆ 20.0   ┆ Debit    │
│                ┆           ┆       ┆ VENMO PAYMENT   ┆   ┆         ┆         ┆        ┆          │
│                ┆           ┆       ┆ A…              ┆   ┆         ┆         ┆        ┆          │
│ ***0530002     ┆ 3/25/2026 ┆ null  ┆ ACH Withdrawal  ┆ … ┆ Wed     ┆ 1       ┆ 639.61 ┆ Debit    │
│                ┆           ┆       ┆ PENNYMAC CASH   ┆   ┆         ┆         ┆        ┆          │
│                ┆           ┆       ┆ B…              ┆   ┆         ┆         ┆        ┆          │
└────────────────┴───────────┴───────┴─────────────────┴───┴─────────┴─────────┴────────┴──────────┘

### Categorize data

In [3]:
# pulls from the categorize py file

from Categorize import make_categories
import Categorize
import importlib
importlib.reload(Categorize)


df = make_categories(df)

df.limit(3)

shape: (3, 11)
┌───────────┬─────────────┬──────────────────┬────────┬───┬──────┬─────────┬──────────┬─────────┐
│ date      ┆ category    ┆ description      ┆ cost   ┆ … ┆ year ┆ weekDay ┆ cardType ┆ quarter │
│ ---       ┆ ---         ┆ ---              ┆ ---    ┆   ┆ ---  ┆ ---     ┆ ---      ┆ ---     │
│ str       ┆ str         ┆ str              ┆ f64    ┆   ┆ i32  ┆ str     ┆ str      ┆ i8      │
╞═══════════╪═════════════╪══════════════════╪════════╪═══╪══════╪═════════╪══════════╪═════════╡
│ 2026-3-31 ┆ natural gas ┆ ACH Withdrawal   ┆ 139.0  ┆ … ┆ 2026 ┆ Tue     ┆ Debit    ┆ 1       │
│           ┆             ┆ SUMMIT SUA BILL… ┆        ┆   ┆      ┆         ┆          ┆         │
│ 2026-3-25 ┆ misc        ┆ ACH Withdrawal   ┆ 20.0   ┆ … ┆ 2026 ┆ Wed     ┆ Debit    ┆ 1       │
│           ┆             ┆ VENMO PAYMENT A… ┆        ┆   ┆      ┆         ┆          ┆         │
│ 2026-3-25 ┆ rent        ┆ ACH Withdrawal   ┆ 639.61 ┆ … ┆ 2026 ┆ Wed     ┆ Debit    ┆ 1       │
│           ┆             ┆ PENNYMAC CASH B… ┆        ┆   ┆      ┆         ┆          ┆         │
└───────────┴─────────────┴──────────────────┴────────┴───┴──────┴─────────┴──────────┴─────────┘

### Look at last month's misc

In [4]:
list(df.filter(pl.col('category') == 'misc')['description'].unique())

['ACH Withdrawal VENMO PAYMENT ADANYA AND BLAKE DENNE']

#### Make sure correct month/year is being loaded

In [5]:
print(list(df['month'].unique()))
print(list(df['monthName'].unique()))
print(list(df['weekDay'].unique()))
print(list(df['year'].unique()))
print(list(df['day'].unique()))
# print(df.select(pl.col("date").min()))
# print(df.select(pl.col("date").max())) # needs fixed, looking at str, not date

[3]
['Mar']
['Sun', 'Thu', 'Mon', 'Tue', 'Wed']
[2026]
[2, 3, 4, 5, 9, 10, 11, 19, 22, 24, 25, 31]

### Check number of rows (40ish per month)
Apr: 38
<br>May: 53
<br>June: 23 - Vegas trip
<br>May: 65
<br>Aug: 48
<br>Sep: 75
<br>Oct: 46
<br>Nov: 66
<br>Dec: 51
<br> 2025 - raising limit on credit card
<br>Jan: 34
<br>Feb: 34
<br>Mar: 15

In [7]:
len(df)

15

### Load the data (handle w/ caution)

In [ ]:
# path = r'C:\Users\Denne\Documents\VSCodeProjects\FinancialStreamline2\BankStreamline\Data\BankDataProd.csv'


# with open(path, mode="a", encoding="utf-8") as f:
#    df.write_csv(f, include_header=False)